
name: ex_check

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-16.04

    steps:
      - uses: actions/checkout@v1.0.0
      - uses: actions/cache@v1
        with:
          path: deps
          key: ${{ runner.os }}-mix-ex_check-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-ex_check-
      - uses: actions/cache@v1
        with:
          path: _build
          key: ${{ runner.os }}-build-ex_check-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-ex_check-
      - run: cp config/dev.exs.example config/dev.exs
      - uses: actions/setup-elixir@v1.0.0
        with:
          otp-version: 23.0
          elixir-version: 1.11.0
      - run: mix deps.get
      - run: MIX_ENV=dev mix check
